stages:
  - build

release:
  only:
    refs:
      - master
      - gitlab_ci_e2e_script
  
  stage: build
  
  image: golang:alpine

  script:
    - export CI=true
    - export VERSION=$CI_PIPELINE_IID
    - apk add --no-cache bash
    - ETE_DIR=$HOME ./scripts/e2e.sh
    - go run cmd/pack/main.go
    - go run main.go -m fff -k $(go run cmd/checksum/main.go) -p .
    - cat scnnr_bins.zip.sha256

  artifacts:
    paths:
      - scnnr_bins.zip
      - scnnr_bins.zip.sha256
      - LICENSE
      - README.md
