stages:
  - build

scnnr_bins:
  only:
    refs:
      - master

  stage: build

  image: docker:stable

  services:
    - docker:dind

  script:
    - docker build -t scnnr_release . --build-arg CI=true --build-arg VERSION=$CI_PIPELINE_IID
    - docker cp scnnr_release:/scnnr_bins.zip scnnr_bins.zip
    - chmod +x scnnr_bins.zip
  
  artifacts:
    paths:
      - scnnr_bins.zip
