stages:
  - build

scnnr_bins:
  only:
    refs:
      - master

  stage: build

  image: docker:stable

  services:
    - docker:dind

  script:
    - ./scripts/chmod.sh
    - ./scripts/dind.build.sh

  artifacts:
    paths:
      - scnnr_bins.zip
