stages:
  - build

release:
  only:
    refs:
      - master

  stage: build

  image: docker:stable

  services:
    - docker:dind

  script:
    - ./scripts/dind.build.sh
    - ls -lahg

  artifacts:
    paths:
      - scnnr_bins
