stages:
  - build

scnnr_bins:
  only:
    refs:
      - master

  stage: build

  image: golang:alpine

  script:
    - apk --update add git && rm -rf /var/cache/apk/*
    - ls -R .
    - VERSION=$CI_PIPELINE_IID CI=true go run cmd/release/main.go 

  artifacts:
    paths:
      - scnnr_bins.zip
