stages:
  - build

scnnr_bins:
  only:
    refs:
      - master

  stage: build

  image: golang:alpine

  script:
    - apk --update add bash && rm -rf /var/cache/apk/*
    - VERSION=$CI_PIPELINE_IID CI=true ./scripts/release.sh

  artifacts:
    paths:
      - scnnr_bins.zip
