stages:
  - build

release:
  only:
    refs:
      - master
  
  stage: build
  
  image: golang:alpine

  script:
    - CI=true VERSION=$CI_PIPELINE_IID go run cmd/pack/main.go

  artifacts:
    paths:
      - scnnr_bins.zip
