stages:
  - docker_build
  - build

release:
  only:
    refs:
      - master

  stage: docker_build

  image: docker:stable

  services:
    - docker:dind

  script:
    - ./scripts/dind.build.sh
  
  stage: build
  
  image: golang

  script:
    - go run cmd/pack/main.go

  artifacts:
    paths:
      - scnnr_bins.zip
