name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: OS Updates
      run: "sudo apt update"
    - name: Build Bins
      run: ./scripts/bins.sh
    - name: E2E
      run: ./scripts/e2e.sh
    - name: Print SHA
      run: cat scnnr_bins.zip.sha256
