name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: OS Deps
      run: "sudo apt-get update"
    - name: Tests
      run: go run cmd/pack/main.go && ls | grep scnnr && go run cmd/checksum/main.go && ls | grep scnnr
