name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: false
    - name: Unit Tests
      run: go test -race ./...
    - name: Vet
      run: go vet ./...
    - name: Build Bins
      run: ./scripts/bins.sh
    - name: E2E
      run: ./scripts/e2e.sh
    - name: Print SHA
      run: cat scnnr_bins.zip.sha256
